package de.hdm.hdmUrlaub.server.db.model;

// Generated 30.12.2014 17:40:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Urlaubsantrag generated by hbm2java
 */
@Entity
@Table(name = "urlaubsantrag", catalog = "mydb")
public class Urlaubsantrag extends HibernateObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4828292215814802589L;
	private Integer id;
	private Mitarbeiter mitarbeiter;
	private Character status;
	private Integer anzahltage;
	private String fachvorgesetzter;
	private String vertretung;
	private Set<Zeitraum> zeitraums = new HashSet<Zeitraum>(0);

	public Urlaubsantrag() {
	}

	public Urlaubsantrag(int id, Mitarbeiter mitarbeiter) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
	}

	public Urlaubsantrag(Integer id, Mitarbeiter mitarbeiter, Character status,
			Integer anzahltage, String fachvorgesetzter, String vertretung,
			Set<Zeitraum> zeitraums) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
		this.status = status;
		this.anzahltage = anzahltage;
		this.fachvorgesetzter = fachvorgesetzter;
		this.vertretung = vertretung;
		this.zeitraums = zeitraums;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mitarbeiter_id", nullable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "anzahltage")
	public Integer getAnzahltage() {
		return this.anzahltage;
	}

	public void setAnzahltage(Integer anzahltage) {
		this.anzahltage = anzahltage;
	}

	@Column(name = "fachvorgesetzter", length = 45)
	public String getFachvorgesetzter() {
		return this.fachvorgesetzter;
	}

	public void setFachvorgesetzter(String fachvorgesetzter) {
		this.fachvorgesetzter = fachvorgesetzter;
	}

	@Column(name = "vertretung", length = 45)
	public String getVertretung() {
		return this.vertretung;
	}

	public void setVertretung(String vertretung) {
		this.vertretung = vertretung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "urlaubsantrag")
	public Set<Zeitraum> getZeitraums() {
		return this.zeitraums;
	}

	public void setZeitraums(Set<Zeitraum> zeitraums) {
		this.zeitraums = zeitraums;
	}

}
