package de.hdm.hdmUrlaub.server.db.model;

// Generated 21.12.2014 16:59:54 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Urlaubsantrag generated by hbm2java
 */
@Entity
@Table(name = "urlaubsantrag", catalog = "mydb")
public class Urlaubsantrag extends HibernateObject {

	private static final long serialVersionUID = 5900487091816780652L;
	private int id;
	private Character status;
	private Integer anzahltage;
	private String fachvorgesetzter;
	private String vertretung;

	public Urlaubsantrag() {
	}

	public Urlaubsantrag(int id) {
		this.id = id;
	}

	public Urlaubsantrag(int id, Character status, Integer anzahltage,
			String fachvorgesetzter, String vertretung) {
		this.id = id;
		this.status = status;
		this.anzahltage = anzahltage;
		this.fachvorgesetzter = fachvorgesetzter;
		this.vertretung = vertretung;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "anzahltage")
	public Integer getAnzahltage() {
		return this.anzahltage;
	}

	public void setAnzahltage(Integer anzahltage) {
		this.anzahltage = anzahltage;
	}

	@Column(name = "fachvorgesetzter", length = 45)
	public String getFachvorgesetzter() {
		return this.fachvorgesetzter;
	}

	public void setFachvorgesetzter(String fachvorgesetzter) {
		this.fachvorgesetzter = fachvorgesetzter;
	}

	@Column(name = "vertretung", length = 45)
	public String getVertretung() {
		return this.vertretung;
	}

	public void setVertretung(String vertretung) {
		this.vertretung = vertretung;
	}

}
