package de.hdm.hdmUrlaub.server.db.model;

// Generated 30.12.2014 17:40:22 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zeitraum generated by hbm2java
 */
@Entity
@Table(name = "zeitraum", catalog = "mydb")
public class Zeitraum extends HibernateObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2137162109841747310L;
	private int id;
	private Urlaubsantrag urlaubsantrag;
	private Date beginn;
	private Date ende;

	public Zeitraum() {
	}

	public Zeitraum(int id, Urlaubsantrag urlaubsantrag) {
		this.id = id;
		this.urlaubsantrag = urlaubsantrag;
	}

	public Zeitraum(int id, Urlaubsantrag urlaubsantrag, Date beginn, Date ende) {
		this.id = id;
		this.urlaubsantrag = urlaubsantrag;
		this.beginn = beginn;
		this.ende = ende;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "urlaubsantrag_id", nullable = false)
	public Urlaubsantrag getUrlaubsantrag() {
		return this.urlaubsantrag;
	}

	public void setUrlaubsantrag(Urlaubsantrag urlaubsantrag) {
		this.urlaubsantrag = urlaubsantrag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "beginn", length = 10)
	public Date getBeginn() {
		return this.beginn;
	}

	public void setBeginn(Date beginn) {
		this.beginn = beginn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ende", length = 10)
	public Date getEnde() {
		return this.ende;
	}

	public void setEnde(Date ende) {
		this.ende = ende;
	}

}
