package de.hdm.hdmUrlaub.server.db.model;

// Generated 21.12.2014 16:59:54 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zeitraum generated by hbm2java
 */
@Entity
@Table(name = "zeitraum", catalog = "mydb")
public class Zeitraum extends HibernateObject {

	private static final long serialVersionUID = -330056528917111562L;
	private int id;
	private Date beginn;
	private Date ende;
	private Integer urlaubsantragId;

	public Zeitraum() {
	}

	public Zeitraum(int id) {
		this.id = id;
	}

	public Zeitraum(int id, Date beginn, Date ende, Integer urlaubsantragId) {
		this.id = id;
		this.beginn = beginn;
		this.ende = ende;
		this.urlaubsantragId = urlaubsantragId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "beginn", length = 10)
	public Date getBeginn() {
		return this.beginn;
	}

	public void setBeginn(Date beginn) {
		this.beginn = beginn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ende", length = 10)
	public Date getEnde() {
		return this.ende;
	}

	public void setEnde(Date ende) {
		this.ende = ende;
	}

	@Column(name = "urlaubsantrag-id")
	public Integer getUrlaubsantragId() {
		return this.urlaubsantragId;
	}

	public void setUrlaubsantragId(Integer urlaubsantragId) {
		this.urlaubsantragId = urlaubsantragId;
	}

}
